require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

Style/Documentation:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'

AllCops:
  NewCops: enable
